# Setup
title: Young's Developer Notes
tagline: ""
description: 'Find more <a href="https://github.com/whyjun" target="_blank">@WHYjun</a>.'
url: ""
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Young Choi
  url: https://github.com/WHYjun
  email: youngchoi.dev@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.0.0

# Category
category_dir: _category/
